To Do List Best Practices Review
ryxtor/To-Do-List-Best-Practices pull request #1
Opened 2022-02-21 20:50 UTC by ryxtor

Hello! 👋🏻 

This is a pull request to check if I'm following the [JavaScript Best Practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md), [DRY, KISS, and YAGNI](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/lesson_DRY_KISS_YAGNI.md) and [HTML & CSS best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) rules.

2022-02-21 23:01 UTC, richardoppiyo requested changes
# Changes required ♻️ 

Kindly check the comment below and work on the changes. 😃 

Thanks

2022-02-21 23:01 UTC, richardoppiyo commented on README.md
> +
I think your README.md file will be better having a single heading that describes the project. Kindly consider removing one heading and description tag.

2022-02-21 23:01 UTC, richardoppiyo commented on src/index.js
> +const runClass = new ToDoList();
To Follow the best JS practice, I suggest you consider having all the declarations at the top of your page for consistency purposes and to make your code even more readable

2022-02-21 23:01 UTC, richardoppiyo commented on src/index.js
> +const btnTask = document.getElementById('enterInput');
To Follow the best JS practice, I suggest you consider having all the declarations at the top of your page for consistency purposes and to make your code even more readable

2022-02-21 23:01 UTC, richardoppiyo commented on src/index.js
> +const enterTask = document.getElementById('input');
To Follow the best JS practice, I suggest you consider having all the declarations at the top of your page for consistency purposes and to make your code even more readable

2022-02-21 23:01 UTC, richardoppiyo commented on src/index.js
> +const delCompletedbtn = document.getElementById('clear-btn');
To Follow the best JS practice, I suggest you consider having all the declarations at the top of your page for consistency purposes and to make your code even more readable

2022-02-21 23:01 UTC, richardoppiyo commented on src/modules/todoclass.js
> +      Array.from(ul.querySelectorAll('li')).forEach((task) => {
You might consider using the shorthand arrow function syntax to make your code even more readable and clean
Consider:

Array.from(ul.querySelectorAll('li')).forEach((task) =>   ul.removeChild(task));

2022-02-21 23:01 UTC, richardoppiyo commented on src/modules/todoclass.js
> +      checkbox.addEventListener('change', () => {
You might consider using the shorthand arrow function syntax to make your code even more readable and clean
Consider:

checkbox.addEventListener('change', () =>   this.completeTask(checkbox.parentElement));

2022-02-21 23:01 UTC, richardoppiyo commented on src/modules/todoclass.js
> +      delIcon.addEventListener('click', () => {
You might consider using the shorthand arrow function syntax to make your code even more readable and clean
Consider:

delIcon.addEventListener('click', () => this.removeTask(task.index));

2022-02-22 15:27 UTC, ryxtor commented
### Hello @richardoppiyo! :wave:

Thanks for your feedback, I've already made the changes. 😄

2022-02-22 16:13 UTC, richardoppiyo approved these changes

2022-02-22 16:16 UTC, richardoppiyo commented
Hello 👋

Great work on implementing the changes 😄

2022-02-24 15:08 UTC, merged